import { TalentProfile, Category } from '@/types';

export const mockTalentProfiles: TalentProfile[] = [
  {
    id: '1',
    userId: 'user-1',
    displayName: 'Winky D',
    bio: 'Zimdancehall king bringing you personalized vibes for your special occasions.',
    category: 'musician',
    thumbnailUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop',
    priceUSD: 50,
    priceZIG: 2500,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 234,
    averageRating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: 'user-2',
    displayName: 'Comic Pastor',
    bio: 'Making Zimbabwe laugh one video at a time. Let me bring joy to your celebrations!',
    category: 'comedian',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    priceUSD: 35,
    priceZIG: 1750,
    isAcceptingBookings: true,
    responseTimeHours: 48,
    adminVerified: true,
    totalBookings: 189,
    averageRating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    userId: 'user-3',
    displayName: 'Janet Manyowa',
    bio: 'Gospel artist spreading love and blessings through personalized messages.',
    category: 'gospel',
    thumbnailUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    priceUSD: 40,
    priceZIG: 2000,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 156,
    averageRating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    userId: 'user-4',
    displayName: 'Stunner',
    bio: 'ZimDancehall heavyweight ready to make your moments unforgettable.',
    category: 'musician',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    priceUSD: 45,
    priceZIG: 2250,
    isAcceptingBookings: true,
    responseTimeHours: 48,
    adminVerified: true,
    totalBookings: 201,
    averageRating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    userId: 'user-5',
    displayName: 'Tendai Mtawarira',
    bio: 'Rugby legend "The Beast" sharing motivation and inspiration.',
    category: 'sports',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    priceUSD: 60,
    priceZIG: 3000,
    isAcceptingBookings: true,
    responseTimeHours: 72,
    adminVerified: true,
    totalBookings: 98,
    averageRating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    userId: 'user-6',
    displayName: 'Mai TT',
    bio: 'Social media sensation bringing laughter and realness to your celebrations.',
    category: 'influencer',
    thumbnailUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    priceUSD: 30,
    priceZIG: 1500,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 312,
    averageRating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const categories: Category[] = [
  { name: 'Musicians', icon: '🎵', count: 45, slug: 'musicians' },
  { name: 'Comedians', icon: '😂', count: 28, slug: 'comedians' },
  { name: 'Gospel', icon: '🙏', count: 32, slug: 'gospel' },
  { name: 'Business', icon: '💼', count: 19, slug: 'business' },
  { name: 'Sports', icon: '⚽', count: 15, slug: 'sports' },
  { name: 'Influencers', icon: '📱', count: 38, slug: 'influencers' },
];
