import { TalentProfile, Category } from '@/types';

export const mockTalentProfiles: TalentProfile[] = [
  {
    id: '1',
    userId: 'user-1',
    displayName: 'Winky D',
    bio: 'Zimdancehall king bringing you personalized vibes for your special occasions.',
    category: 'musician',
    thumbnailUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEibVl33NY0ZgzerdWL_xjAVlIT7YS5x6hqRAjf1gOoJYB4QnKsk8ZLDh46xI31hAqEV2lgQqPNuZ_pW10qtDENgdtb_MD2N-W-duoFIJ8bleQrD3LS_GE-TdXy-FmQARJ6Z_qUhXIbtHDzD/s16000/Copy+of+Marcus+Fixed+Rate+Blue+Finance+Animated-1080x1080px-InstagramPost+%252845%2529.png',
    priceUSD: 50,
    priceZIG: 2500,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 234,
    averageRating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: 'user-2',
    displayName: 'Comic Pastor',
    bio: 'Making Zimbabwe laugh one video at a time. Let me bring joy to your celebrations!',
    category: 'comedian',
    thumbnailUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi3qwVe52lTQ02MnrdlgLC8HOfkv0v5XZ5dJeHc-NMVbzdujwlcC0yxLI5vGY4Vi4FnUO4Ez2IDaPtublyPTl1EnuXrklKSkVKJd8R-Ax60KW1XOSDoGHLDksCs9zVmRF7nkmg62RUvzd1d/s1400/comic-pastor.jpg',
    priceUSD: 35,
    priceZIG: 1750,
    isAcceptingBookings: true,
    responseTimeHours: 48,
    adminVerified: true,
    totalBookings: 189,
    averageRating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    userId: 'user-3',
    displayName: 'Jah Prayzah',
    bio: 'Award-winning Afro-fusion artist ready to make your special moments legendary.',
    category: 'musician',
    thumbnailUrl: 'https://dailynews.co.zw/wp-content/uploads/2025/05/Jah-Prayzah.jpg',
    priceUSD: 60,
    priceZIG: 3000,
    isAcceptingBookings: true,
    responseTimeHours: 48,
    adminVerified: true,
    totalBookings: 312,
    averageRating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    userId: 'user-4',
    displayName: 'Minister Mahendere',
    bio: 'Gospel minister bringing spiritual blessings and encouragement to your celebrations.',
    category: 'gospel',
    thumbnailUrl: 'https://cdn.thestandard.co.zw/images/newsday/uploads/2025/08/8eJnh7HT0HIRWonOvDzRHm090JT6USuS2edgLUSL.jpg',
    priceUSD: 45,
    priceZIG: 2250,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 178,
    averageRating: 5.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    userId: 'user-5',
    displayName: 'Tendai Mtawarira',
    bio: 'Rugby legend "The Beast" sharing motivation and inspiration.',
    category: 'sports',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    priceUSD: 60,
    priceZIG: 3000,
    isAcceptingBookings: true,
    responseTimeHours: 72,
    adminVerified: true,
    totalBookings: 98,
    averageRating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    userId: 'user-6',
    displayName: 'Mai TT',
    bio: 'Social media sensation bringing laughter and realness to your celebrations.',
    category: 'influencer',
    thumbnailUrl: 'https://i0.wp.com/nehandaradio.com/wp-content/uploads/2025/06/Mai-TT.jpg?fit=1280%2C1023&ssl=1',
    priceUSD: 30,
    priceZIG: 1500,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 312,
    averageRating: 4.6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    userId: 'user-7',
    displayName: 'Madam Boss',
    bio: 'Queen of comedy bringing hilarious skits and laughter to your special occasions.',
    category: 'comedian',
    thumbnailUrl: 'https://nehandaradio.com/wp-content/uploads/2025/06/Madam-Boss-BET-Awards-2025-12.webp',
    priceUSD: 40,
    priceZIG: 2000,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 267,
    averageRating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    userId: 'user-8',
    displayName: 'Mai TT',
    bio: 'High-energy entertainer known for vibrant performances and unforgettable messages.',
    category: 'influencer',
    thumbnailUrl: 'https://i0.wp.com/nehandaradio.com/wp-content/uploads/2025/06/Mai-TT.jpg?fit=1280%2C1023&ssl=1',
    priceUSD: 35,
    priceZIG: 1750,
    isAcceptingBookings: true,
    responseTimeHours: 48,
    adminVerified: true,
    totalBookings: 145,
    averageRating: 4.7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    userId: 'user-9',
    displayName: 'Comic Elder',
    bio: 'Veteran comedian delivering timeless humor and heartfelt messages for all ages.',
    category: 'comedian',
    thumbnailUrl: 'https://www.pindula.co.zw/images/thumb/7/74/Comic-Elder.jpg/1024px-Comic-Elder.jpg',
    priceUSD: 30,
    priceZIG: 1500,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 198,
    averageRating: 4.9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    userId: 'user-10',
    displayName: 'Yahyah Good Vibes',
    bio: 'Spreading positivity and good vibes through personalized video messages.',
    category: 'influencer',
    thumbnailUrl: 'https://www.zimbabwenow.co.zw/assets/uploads/2024/editor-files/e29c1702-cbf8-417c-8c4d-3fc6f9d30d4a.jpg',
    priceUSD: 25,
    priceZIG: 1250,
    isAcceptingBookings: true,
    responseTimeHours: 24,
    adminVerified: true,
    totalBookings: 156,
    averageRating: 4.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const categories: Category[] = [
  { name: 'Musicians', icon: '🎵', count: 45, slug: 'musicians' },
  { name: 'Comedians', icon: '😂', count: 28, slug: 'comedians' },
  { name: 'Gospel', icon: '🙏', count: 32, slug: 'gospel' },
  { name: 'Business', icon: '💼', count: 19, slug: 'business' },
  { name: 'Sports', icon: '⚽', count: 15, slug: 'sports' },
  { name: 'Influencers', icon: '📱', count: 38, slug: 'influencers' },
];
